import type { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
  return await knex.raw(`
    create table semester_school_year(
      id int generated by default as identity primary key,
      semester int not null,
      first_year varchar(4) not null,
      second_year varchar(4) not null
    );
    insert into semester_school_year(semester, first_year, second_year) values (1, '2021', '2022');
    insert into semester_school_year(semester, first_year, second_year) values (2, '2021', '2022');
    insert into semester_school_year(semester, first_year, second_year) values (1, '2022', '2023');
    insert into semester_school_year(semester, first_year, second_year) values (2, '2022', '2023');
    insert into semester_school_year(semester, first_year, second_year) values (1, '2023', '2024');
    insert into semester_school_year(semester, first_year, second_year) values (2, '2023', '2024');
    insert into semester_school_year(semester, first_year, second_year) values (1, '2024', '2025');
    insert into semester_school_year(semester, first_year, second_year) values (2, '2024', '2025');
  `)
}


export async function down(knex: Knex): Promise<void> {
  return await knex.raw(`
    drop table semester_school_year;
  `);
}

