import type { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    create table role(
      id int generated by default as identity primary key,
      name varchar(50) not null
    );
    alter table teacher add column role_id int references role(id);
  `);
}


export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
    alter table teacher drop column role_id;
    drop table role;  
  `)
}

