
import { Knex } from 'knex';
 
export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    create table teacher (
      id int generated by default as identity primary key,
      name varchar(50) not null,
      username VARCHAR(50) unique not null,
      password varchar(50) not null,
      created_at timestamp not null,
      last_login timestamp
    );
  `);
}
 
export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
    drop table teacher
  `);
}