import type { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    create table question_level(
      id int generated by default as identity primary key,
      name varchar(255) not null,
      deleted boolean default false
    );
    insert into question_level(name) values ('easy');
    insert into question_level(name) values ('medium');
    insert into question_level(name) values ('complex');
    insert into question_level(name) values ('hard');
  `)
}


export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
    drop table question_level;
  `)
}

