import type { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    create table course(
      id int generated by default as identity primary key,
      name varchar(255) not null
    );
    insert into course(name) values('Introduction to Programming');
    insert into course(name) values('Object Oriented Programming');
    insert into course(name) values('Data Structure and Algorithm');
    insert into course(name) values('Database Management System');
  `)
}


export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
    drop table course;
  `)
}

