import type { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
  return await knex.raw(`
    create table exam(
      id int generated by default as identity primary key,
      total_score int not null,
      time int not null,
      exam_date date not null,
      course_id int not null,
      semester_school_year_id int not null,
      teacher_id int not null,
      created_at timestamp default current_timestamp,
      deleted boolean default false,
      foreign key(course_id) references course(id),
      foreign key(semester_school_year_id) references semester_school_year(id),
      foreign key(teacher_id) references teacher(id)
    );
  `)
}


export async function down(knex: Knex): Promise<void> {
  return await knex.raw(`
    drop table exam;
  `);
}

