import type { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    create type permission_name as enum(
    'teacher:modify', 
    'teacher:read',
    'question:modify', 
    'question:read',
    'exam:modify',
    'exam:read',
    'grade:modify',
    'grade:read',
    'report:read'
    );
    create table permission_based(
      id int generated by default as identity primary key,
      role_id int references role(id),
      permission permission_name  
    );
  `);
}


export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
    drop type permission_name;
    drop table permission_based;
  `)
}

