import type { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    create table question(
      id int generated by default as identity primary key,
      content varchar(255) not null,
      deleted boolean default false,
      course_id int not null,
      question_level_id int not null,
      teacher_id int not null,
      foreign key(course_id) references course(id),
      foreign key(question_level_id) references question_level(id),
      foreign key(teacher_id) references teacher(id)
    );
  `)
}


export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
    drop table question;
  `)
}

